Massive refactor and cleanup

diff --git a/project1/stats b/project1/stats
--- a/project1/stats
+++ b/project1/stats
@@ -1,99 +1,44 @@
 #!/bin/sh
 
-AVERAGES=()
-MEDIANS=()
-FILE_LIST=$$"FILE_LIST"
-INPUT_FILE=$$"infile"
-COL_FILE_BASE=$$"col"
-ROW_FILE_BASE=$$"row"
+INPUT_FILE="stats_input$$"
+TMP_FILE="stats_tmp$$"
 
-
-separate_rows () {
-    local ROW=0
-
-    if [ ! -e $INPUT_FILE ]
-    then
-        return 1
-    fi
-
+function rows () {
+    printf "Average\tMedian\n"
     while read line
     do
-        # increment row count -- for temporary file naming
-        local ROW=$(( $ROW + 1 ))
-
-        # create temporary file to store row
-        local FILE=$ROW_FILE_BASE$ROW
-        # add temporary file name to file list
-        echo $FILE >> $FILE_LIST
-
         # write row, newline separated, to temporary file
-        printf "%s\n" $line > $FILE
+        printf "%s\n" $line > $TMP_FILE
+
+        # sort temporary file
+        sort $TMP_FILE -n -o $TMP_FILE
+
+        # print average and median for row
+        printf '%s\t%s\n' $(calculate_average) $(calculate_median)
     done < $INPUT_FILE
 }
 
-separate_columns () {
+function columns () {
+    local AVERAGES=()
+    local MEDIANS=()
+
     local ROWS=$(wc -l < $INPUT_FILE)   # number of rows in file
     local WORDS=$(wc -w < $INPUT_FILE)  # number of numbers in file
     local COLS=$(( $WORDS / $ROWS ))    # calculate number of columns in file
 
     for COL in $(seq 1 $COLS)
     do
-        # create temporary file to store column
-        local FILE=$COL_FILE_BASE$COL
-        # add temporary file name to file list
-        echo $FILE >> $FILE_LIST
-
+        $(> $TMP_FILE)
         while read LINE
         do
             # write column to temporary file
-            echo $LINE | cut -d" " -f $COL >> $FILE
+            echo $LINE | cut -d" " -f $COL >> $TMP_FILE
         done < $INPUT_FILE
+        sort $TMP_FILE -n -o $TMP_FILE
+        AVERAGES+=($(calculate_average))
+        MEDIANS+=($(calculate_median))
     done
-}
 
-# sort each file in $FILE_LIST from least to greatest
-sort_files() {
-    while read line
-    do
-        sort $line -n -o $line
-    done < $FILE_LIST
-}
-
-# calculate average...
-calculate_averages() {
-    while read line
-    do
-        local SUM=0
-        local COUNT=0
-        while read -r num
-        do
-            (( SUM += num ))
-            (( COUNT += 1 ))
-        done < $line
-        local AVERAGE=$( echo $SUM / $COUNT + 0.5 | bc -l )
-        AVERAGES+=(${AVERAGE%.*})
-    done < $FILE_LIST
-}
-
-calculate_medians() {
-    while read line
-    do
-        local NUMS=$(wc -l < $line)
-        local MEDIAN_INDEX=$(( ($NUMS / 2) + 1 ))
-        MEDIANS+=($( head -$MEDIAN_INDEX $line | tail -1 ))
-    done < $FILE_LIST
-}
-
-print_results_rows() {
-    printf "Average\tMedian\n"
-   # LENGTH=${#AVERAGES[@]}
-    for i in "${!AVERAGES[@]}"
-    do
-        printf '%s\t%s\n' ${AVERAGES[$i]} ${MEDIANS[$i]}
-    done
-}
-
-print_results_cols() {
     echo Averages:
     printf "%s\t" "${AVERAGES[@]}"
     printf "\n"
@@ -102,20 +47,33 @@ print_results_cols() {
     printf "\n"
 }
 
-clean_up() {
-    rm -f *row*
-    rm -f *col*
-    rm -f $$"FILE_LIST"
-    rm -f *infile
+function calculate_average() {
+    local SUM=0
+    local COUNT=0
+    local AVERAGE=0
+
+    while read -r num
+    do
+        (( SUM += num ))
+        (( COUNT += 1 ))
+    done < $TMP_FILE
+    AVERAGE=$( echo $SUM / $COUNT + 0.5 | bc -l )
+    echo ${AVERAGE%.*}
 }
 
-common_operations() {
-    sort_files
-    calculate_averages
-    calculate_medians
+function calculate_median() {
+    local NUMS=$(wc -l < $TMP_FILE)
+    local MEDIAN_INDEX=$(( ($NUMS / 2) +1 ))
+    echo $( head -$MEDIAN_INDEX $TMP_FILE | tail -1 )
 }
 
-# get command line args
+function clean_up() {
+    rm -f $TMP_FILE
+    rm -rf "stats_input$$"
+}
+
+trap clean_up EXIT
+
 if [ "$#" = "1" ]
 then
     cat > $INPUT_FILE
@@ -126,7 +84,14 @@ fi
 
 if [ ! -r $INPUT_FILE ]
 then
-    echo "stats: cannot read ${INPUT_FILE}"
+    >&2 echo "${0}: Cannot read ${INPUT_FILE}"
+    clean_up
+    exit 1
+fi
+
+if [ ! -s $INPUT_FILE ]
+then
+    >&2 echo "Usage: stats {-rows|-cols} [file]" 2>&1
     clean_up
     exit 1
 fi
@@ -134,21 +99,13 @@ fi
 if [[ $1 == -r* ]];
 then
     # separate files into rows **NEEDS ERROR HANDLING**
-    separate_rows
-
-    common_operations # ** NEEDS ERROR HANDLING **
-
-    print_results_rows # ** NEEDS ERROR HANDLING **
+    rows
 elif [[ $1 == -c* ]];
 then
     # separate files into cols ** NEEDS ERROR HANDLING**
-    separate_columns
-
-    common_operations # ** NEEDS ERROR HANDLING **
-
-    print_results_cols # ** NEEDS ERROR HANDLING **
+    columns
 else
-    echo "Usage: stats {-rows|-cols} [file]"
+    >&2 echo "Usage: stats {-rows|-cols} [file]"
     clean_up
     exit 1
 fi
